// Chat
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const USER_JOIN_ROOM = "USER_JOIN_ROOM";
export const USER_LEAVE_ROOM = "USER_LEAVE_ROOM";
export const RECEIVE_ROOM_USERLIST = "RECEIVE_ROOM_USERLIST";
export const RECEIVE_MESSAGE = "RECEIVE_MESSAGE";
